### ISSUE TITLE
flashpoint 9.0

### ISSUE THREAD

**Issue by gimmeAll** [FlashpointProject/FlashpointUltimateUpdater#3]
Its not an issue, more of a question. On the official bluemaxima site it only lets you download the newest version which is 8.2, yet with this updater there is a new version 9.0. Just wondering why it is available to update to with this software but not on the official site.

**Comment by XXLuigiMario** [comment]
During the release process, server-side changes are made hours ahead of release.
It would be possible to get an early look at the new release provided a good internet connection.
Flashpoint 9.0 is now also available from https://bluemaxima.org/flashpoint/downloads/
