### ISSUE TITLE
Untenable download speed from 8.2 > 10

### ISSUE THREAD

**Issue by nyghtly-derek** [FlashpointProject/FlashpointUltimateUpdater#6]
Using the command line to update from 8.2 to 10, I am getting the following report:

Downloading new data...
  0%|2                                                                | 1499/371096 [1:49:25<141:30:03,  1.38s/file]
  
Surely it would be faster to download the the entire archive than it is to use the updater. Am I missing something?

**Comment by chunkynutella** [comment]
also getting this issue with the GUI version
